### ISSUE TITLE
Low - Increase buttons size

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNIST#11]
Increase button size and/or make them a bit further apart from each other so there is no risk to click on the wrong button, especially on smartphone

**Comment by migusta** [comment]
Added in new version

**Comment by GregVial** [comment]
Yes I like the size. 
One concern though is that the page doesn't display on one screen anymore, both on PC and smartphone. This is due to the too big size of the logo. I will ask to get it with a smaller C and if required we can also make it smaller on display
