### ISSUE TITLE
Medium - gamification

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNIST#12]
In order to retain users and encourage them to draw up to 100 images:
- add a visible counter of how many letters they have drawn
- add a grade : first grade up to 5, then up to 20, then up to 50 , then up to 100 (I mentioned military grades, but better find something else not related to army, could be beginner, junior, medium, advanced, expert, or kitten, cat, leopard, tiger, lion or anything else you please)
- add an image that matches the grade
- add a small animation when the new grade is reached

**Comment by migusta** [comment]
I'm not sure about mobile version of user rate, if you have thoughts, I can modify. But all functionality is done in the new version

**Comment by GregVial** [comment]
I love it :) Well done!
