### ISSUE TITLE
Nice to have - share on facebook

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNIST#14]
It would be nice to have a "share on facebook" button on the final page, don't know how complicated that is though, if too hard don't bother.

**Comment by migusta** [comment]
Added

**Comment by GregVial** [comment]
Yes that looks good, the only thing I would like to add is that when you click it, it just says "CoMNIST", I suppose it comes from the html page? It would be good if it said "CoMNIST, learning to write made easy"

**Comment by migusta** [comment]
I added your domain on fb link, so you need to test with new title tag from your server.

**Comment by GregVial** [comment]
I modified the link to comnist.gregvi.al
Once you integrate this change you can close this issue.
