### ISSUE TITLE
Low - french version

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNIST#15]
Texte "Dessine-moi un <letter> majuscule"
Button 1 "Oups, je veux réessayer"
Button 2 "Suivante!"
Button 3 "Ca suffit pour l'instant"

Texte "Merci de remplir ton nom si tu veux apparaître sur la page de remerciement. Tu peux aussi laisser ton adresse email si tu veux être informé des progrès de ce projet (promis, pas de spam!)"

Texte "Merci! Tu peux essayer la version russe ici. N'hésite pas à partager avec tes amis et à faire participer ta famille, en particulier les enfants"

**Comment by GregVial** [comment]
I believe it's ok, if not bug on your side can be closed

**Comment by migusta** [comment]
According to the code, everything is ok!
