### ISSUE TITLE
Low - Add subtitle

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNIST#16]
Below CoMNIST, add a subtitle:
"Learning to write made easy"
"Faciliter l'apprentissage de l'écriture"
I let you translate to russian :)

**Comment by migusta** [comment]
Added in english, check the position, have doubts if I get it right

**Comment by GregVial** [comment]
Yes position is fine, that's how I imagined it

**Comment by migusta** [comment]
Close this one?
