### ISSUE TITLE
Medium - improve mobile display

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNIST#21]
To me the PC version is perfect - I love it :)

Now we probably need to brainstorm the mobile version to make it more user-friendly, I am afraid users will lose patience if scrolling up/down all the time. 
It will probably involve displaying small picture/text...
Potentially the buttons can be converted to images to save space (no text): we could have an eraser, a "play" symbol (black triangle pointing right) and a "stop" symbol (black square)
Just some ideas. Your creativity is welcome!

**Comment by migusta** [comment]
Need your approve:)

**Comment by GregVial** [comment]
I approve your changes :) 
Any chance to make it fit on one single page on mobile? I think reducing the buttons (replace text with icons) and displaying the gamification to the right of the drawing screen should help.
If required the drawing screen size can be slightly reduced too.

**Comment by migusta** [comment]
Check new version on your mobile https://migusta.000webhostapp.com/ here - reduced width of the letter drawing area to 240
