### ISSUE TITLE
High - On mobile the page doesn't resize and appears very small

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNIST#7]
![screenshot_2017-02-17-22-18-03](https://cloud.githubusercontent.com/assets/15802765/23083666/1cfd2d08-f55f-11e6-8e89-6270f4261baf.png)

Need to ensure the display adapts to mobile devices screen
See screen shot from my mobile (Samsung galaxy S3), the writting window is tiny

**Comment by migusta** [comment]
Adding styles will fix it;)

**Comment by migusta** [comment]
Test on your phone and close this issue, if everything is ok

**Comment by GregVial** [comment]
Yes it looks good now! Thanks :)
